name: lang_detect
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - openssl=3.0.8
  - pip=23.0.1
  - python=3.8.16
  - setuptools=67.5.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - blis==0.7.9
    - catalogue==2.0.8
    - certifi==2022.12.7
    - click==8.1.3
    - colorama==0.4.6
    - confection==0.0.4
    - cymem==2.0.7
    - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl
    - flask==2.2.3
    - idna==3.4
    - importlib-metadata==6.0.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - langcodes==3.3.0
    - langdetect==1.0.9
    - markupsafe==2.1.2
    - murmurhash==1.0.9
    - numpy==1.24.2
    - pandas==1.5.3
    - pathy==0.10.1
    - preshed==3.0.8
    - pybind11==2.10.3
    - pydantic==1.10.5
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - requests==2.28.2
    - six==1.16.0
    - smart-open==6.3.0
    - spacy==3.5.0
    - spacy-language-detection==0.2.1
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.6
    - thinc==8.1.8
    - tqdm==4.65.0
    - typer==0.7.0
    - typing-extensions==4.5.0
    - urllib3==1.26.14
    - wasabi==1.1.1
    - werkzeug==2.2.3
    - zipp==3.15.0
